#  Görüntü İşleme Dersi İçin Python'da Matrisler


In [2]:
#Bilindiği üzere Numpy Kütüphanesi sayısal işlemler için kullanılır

import numpy as np

In [4]:
A= [[1,4,5],
   [-5,8,9],
   [6,8,10],   #Görüldüğü gibi bir marisin elemanlarını elimizle girebiliriz!
   [0,2,38]]

In [5]:
print("A= ",A) #A matrisini yazdırmak istersek

A=  [[1, 4, 5], [-5, 8, 9], [6, 8, 10], [0, 2, 38]]


In [9]:
print("A[0]", A[0]) #indekslere numaralarını girebiliriz ve istediğimiz satırları ekrana yazdırabiliriz!

A[0] [1, 4, 5]


In [10]:
print("A[1]", A[1])

A[1] [-5, 8, 9]


In [11]:
print("A[2]", A[2])

A[2] [6, 8, 10]


In [12]:
print("A[3]", A[3])

A[3] [0, 2, 38]


In [14]:
print("A[1][2] =", A[1][2]) #Görüldüğü üzere satırlardaki istediğimiz elemanı da bu formatta yazdırabiliriz!

A[1][2] = 9


In [15]:
# Numpy da Array oluşturmak istersek:


In [18]:
a= np.array([[1,7,9],
            [-9,7,2],
            [6,7,2],
           [10,3,-4]])
a

array([[ 1,  7,  9],
       [-9,  7,  2],
       [ 6,  7,  2],
       [10,  3, -4]])

In [19]:
#Python da bir klasiktir. Değişkenimizin tipine bakalım
print("type:", type(a))

type: <class 'numpy.ndarray'>


In [20]:
print("a =","\n", a, "\n") 

a = 
 [[ 1  7  9]
 [-9  7  2]
 [ 6  7  2]
 [10  3 -4]] 



In [21]:
print(a)

[[ 1  7  9]
 [-9  7  2]
 [ 6  7  2]
 [10  3 -4]]


In [22]:
#aynı şekilde satırları ve istediğimiz elemanları yazdırmak istersek 

print("a[1]= ", a[1])

a[1]=  [-9  7  2]


In [24]:
#ikinci bir index numarasıyla istenilen bir eleman yazdıralım

print("a[1][2]= ", a[1][2])

a[1][2]=  2


In [29]:
# for döngüsü yardımıyla a matrisini yazdırmak istersek

for i in a:
    for j in i:
        print("{:>5}".format(j),end="")
        print()

    1
    7
    9
   -9
    7
    2
    6
    7
    2
   10
    3
   -4


In [30]:
# MATRİS TÜRLERİ 
#farklı matris çeşitleri bulunmaktadır. Kare matris (satır ve sütun sayısı birbirine eşit)

In [33]:
np.array(range(9)).reshape(3,3) #range ve reshape methodları beraber kulalnılarak belirlediğimiz aralıkta belirlediğimiz ölçüde
                                #matris oluşturabiliriz..3x3 kare matrisssss

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
#sıfır matrisin tüm elemanlarının sıfır olduğu bir matris zeros() methoduyla

np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.zeros((6,6),dtype="int")

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [45]:
#sadece bir tane satırı olana satır matrisi , tek bir sütunu olan ise sütun matrisi denir
print(np.array([[1,7,9]]))
print("shape: ", np.array([[1,7,9]]).shape) ##Satır matrisi: 1x3 boyutlu, satır sayısı 1

[[1 7 9]]
shape:  (1, 3)


In [46]:
print(np.array([[1],[7],[9]]))
print("shape: ", np.array([[1,7,9]]).shape) ##Satır matrisi: 1x3 boyutlu, satır sayısı 1

[[1]
 [7]
 [9]]
shape:  (1, 3)


In [48]:
#Köşegen elemanları dışındaki tüm elemanları 0 olan matris ise köşegen matris olarak bilinir. 
#Sadece kare matrisler, köşegen matris olabilir. (köşegen en. diagonal ;)
np.diag(np.diag(np.array(range(1,26)).reshape(5,5)))


array([[ 1,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 19,  0],
       [ 0,  0,  0,  0, 25]])

In [49]:
#Matris kare iken (yani n=p iken), köşegen elemanların 1 kalan elemanların 
#0 olduğu matris ise birim matristir. (birim matris I ile gösterilir mat)

np.identity(7, dtype="int")

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [50]:
#Esas köşegen üzerindeki elemanları aynı olup kalan elemanları 0 olan matris ise skaler 
#matris olarak isimlendirilir. Birim matrisin bir skaler ile çarpılması sonucu elde edilir.
np.identity(7, dtype="int")*30


array([[30,  0,  0,  0,  0,  0,  0],
       [ 0, 30,  0,  0,  0,  0,  0],
       [ 0,  0, 30,  0,  0,  0,  0],
       [ 0,  0,  0, 30,  0,  0,  0],
       [ 0,  0,  0,  0, 30,  0,  0],
       [ 0,  0,  0,  0,  0, 30,  0],
       [ 0,  0,  0,  0,  0,  0, 30]])

In [51]:
#Matrislerde işlemlerde en önemlisi TRANSPOZE işlemi .T yeterlidir

X= np.array(range(12)).reshape(6,2) #6x2 lik bir matris
X
 


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [52]:
#Transpoze işlemi 
X.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [54]:
#Traspoze işlemini açmak istersem satırların sütun olması ve sütunların satır olması.Döngü ile yapalım
X= np.array(range(12)).reshape(4,3) #4x3 lük bir matris oluşturduk
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
zeros= np.zeros((3,4), dtype="int") #3x4 lük matris oluşturduk, x'in transpozunu buraya ekleyeceğiz


In [57]:
for i in range(len(X)):
    for j in range(len(X[0])):
        zeros[j][i]=X[i][j]
        

print(zeros)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [58]:
#List comprehension ile devrik matris oluşturma
X= np.array(range(12)).reshape(4,3) #4x3 lük bir matris oluşturduk
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
zeros= np.zeros((3,4), dtype="int") #3x4 lük matris oluşturduk, x'in transpozunu buraya ekleyeceğiz

In [65]:
for i in [ [X[i][j] for i in range(len(X))] for j in range(len(X[0]))]:
    print(i)

[0, 3, 6, 9]
[1, 4, 7, 10]
[2, 5, 8, 11]


In [66]:
# Matrislerde Toplama Ve Çıkarma İşlemleri


In [67]:
#lineer cebirden de hatırlayacağımız gibi toplama ve çıkarma işlemleri için matrislerin aynı boyutta
#olması için

m1= np.random.randint(20, size=(5,3))
m1

array([[19,  9,  1],
       [ 7,  9, 18],
       [11,  2, 11],
       [ 2, 11, 17],
       [ 2,  5,  9]])

In [68]:
m2= np.random.randint(5, size=(5,3))
m2

array([[1, 4, 4],
       [4, 2, 4],
       [1, 4, 0],
       [0, 0, 3],
       [2, 4, 3]])

In [69]:
#toplama:
m1+m2

array([[20, 13,  5],
       [11, 11, 22],
       [12,  6, 11],
       [ 2, 11, 20],
       [ 4,  9, 12]])

In [70]:
#çıkarma:
m1-m2

array([[18,  5, -3],
       [ 3,  7, 14],
       [10, -2, 11],
       [ 2, 11, 14],
       [ 0,  1,  6]])

In [71]:
#Matrislerde çarpma işlemi için Birincinin sütun sayısı ile ikincinin satır sayısı eşit olamlıdır
#aynı zamanda sabit sayılarla da çarpılabilir

m1*56

array([[1064,  504,   56],
       [ 392,  504, 1008],
       [ 616,  112,  616],
       [ 112,  616,  952],
       [ 112,  280,  504]])

In [73]:
#matris* matris için

a1= np.random.randint(5, size=(5,3))
a1

array([[0, 3, 4],
       [2, 1, 1],
       [3, 2, 2],
       [2, 1, 1],
       [4, 4, 1]])

In [74]:
a2= np.random.randint(2,size=(3,4))
a2


array([[1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])

In [77]:
result= np.zeros((5,4))

In [79]:
for i in range(a1.shape[0]):
    for j in range(a2.shape[1]):
        for k in range(a2.shape[0]):
            result[i][j]+= a1[i,k]* a2[k,j]
            
result

array([[14.,  6.,  6.,  6.],
       [ 8.,  2.,  2.,  2.],
       [14.,  4.,  4.,  4.],
       [ 8.,  2.,  2.,  2.],
       [18.,  8.,  8.,  8.]])

In [ ]:
#1. Adım: İlk matrisin ilk satırı ile ikinci matrisin ilk sütunu birebir eşlenerek çarpılır, 
#bu çarpımlar toplanır,sonuç matrisinde result[0][0]’lık kısma yazılır.
#2. Adım: İlk matrisin ilk satırı ile ikinci matrisin ikinci sütunu birebir eşlenerek çarpılır,
#bu çarpımlar toplanır, sonuç matrisinde result[0][1]’lık kısma yazılır.
#3. Adım: İlk matrisin ilk satırı ile ikinci matrisin üçüncü sütunu birebir eşlenerek çarpılır, 
#bu çarpımlar toplanır,sonuç matrisinde result[0][2]’lık kısma yazılır.
#4. Adım: İlk matrisin ilk satırı ile ikinci matrisin dördüncü sütunu birebir eşlenerek çarpılır, 
#bu çarpımlar toplanır, sonuç matrisinde result[0][3]’lık kısma yazılır.
#5. Adım: İlk arrayin ilk satırı için işlemleri tamamlandı. 
#Bu dört adım ilk arrayin her bir satırı için yapılır.
