# BGR LOGIC

In [30]:
import cv2 
import numpy as np

In [31]:
#image.jpg resmini okuyup newYork isimli değişkene atadık.
newYork = cv2.imread("image.jpg")  

In [32]:
#Resmin ekranda görüntülenmesini sağladık.
cv2.imshow("NewYork City", newYork ) 

In [35]:
print(newYork) #Resmin Matris Görünümünü elde etmek için:

[[[231 200 167]
  [230 199 166]
  [229 198 165]
  ...
  [237 222 203]
  [237 222 203]
  [238 223 204]]

 [[237 206 173]
  [237 206 173]
  [236 205 172]
  ...
  [231 216 197]
  [231 216 197]
  [232 217 198]]

 [[237 209 175]
  [236 208 174]
  [235 207 173]
  ...
  [229 211 194]
  [230 212 195]
  [231 213 196]]

 ...

 [[196 190 185]
  [192 188 183]
  [195 192 187]
  ...
  [ 53  55  56]
  [ 49  51  52]
  [ 56  58  59]]

 [[190 194 188]
  [192 196 190]
  [194 194 188]
  ...
  [ 67  68  72]
  [ 36  37  41]
  [ 17  18  22]]

 [[192 203 195]
  [186 194 187]
  [192 192 186]
  ...
  [ 74  75  79]
  [118 119 123]
  [138 139 143]]]


# # BGR-PIXSEL

In [2]:
newYork= cv2.imread("image.jpg")

In [3]:
cv2.imshow("New York City",newYork )

In [4]:
#Bgr değerlerini görmek için
print(newYork[(150,90)])

[240 230 220]


In [5]:
#Resmin aşağı doğru 150, sağa doğru 80 pixel değerini belirtmiş olduk. Çıktıda ilgili pikselin BGR değerlerini görürüz.

In [7]:
print("Resmin boyutu: " + str(newYork.size))  #print de string ifade yazdığımız için stringe çevirdik.c# ın tersine


Resmin boyutu: 2880000


In [8]:
print(newYork.size) #Bu şekilde de görüntüleyebiliyoruz.

2880000


In [9]:
print(newYork.shape) #Resmimizin de özelliklerini bu şekilde görüntüleyebilriz.

(800, 1200, 3)


In [11]:
print("Resmin özellikleri: "+ str(newYork.size)) #Str olarak belirtmek sebebimizi yukarıda belirttik


Resmin özellikleri: 2880000


In [14]:
print(newYork.dtype) #Son olarak da veri tipini görelim!

uint8


In [16]:
print("Resimin veri tipi: "+ str(newYork.dtype))

Resimin veri tipi: uint8


In [17]:
cv2.waitKey(0)
cv2.destroyAllWindows()